### ISSUE TITLE
US-008 - Ajouter une entreprise

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#10]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-001 | FE-001, FE-174 |

## User Story

Sur la page “Paramètres du compte”.
Sur cette page il y un formulaire pour ajouter les informations d’une entreprise, le formulaire demande les informations suivantes :

- Type (Société, EI, Association)
- Nom
- Numéro de SIRET
- Numéro de TVA
- Adresse

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Enregistrer”, qui permet d’enregistrer les modifications.
Je clique sur le bouton “Enregistrer”.

## Tasks

- [ ] TF-053 | Créer le formulaire
- [ ] TF-054 | Modifier la page compte
- [ ] TF-055 | Vérifier que tous les champs sont valide
- [ ] TF-056 | Rédaction des tests
- [ ] TF-057 | Résolution des bugs
