### ISSUE TITLE
US-012 - Lister l’ensemble des projets

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#13]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-002 | FE-087 |

## User Story

Sur la page “Projets”.
Il y a la liste de mes projets au format tableau

## Tasks

- [ ] TF-070 | Créer la page  "Mes projets"
- [ ] TF-071 | Rédaction des tests
- [ ] TF-072 | Résolution des bugs
