### ISSUE TITLE
US-013 - Ajouter un projet

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#14]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-013 |

## User Story

Sur la page liste des projets, un bouton en haut à droite me permet d’accéder au formulaire d’ajout.

Je clique sur le bouton, un popup s’ouvre sur avec un formulaire qui demande : 
- url du projet

Je clique sur le bouton « Créer » afin d’enregistrer le projet.

Si les données fournies sont valides, le popup se ferme et la liste des projets est mise à jour pour faire apparaître le nouveau projet.

## Exceptions

1. Étant donné qu’une url doit être valide, si elle ne correspond pas le champ devient rouge et un message est affiché à côté de celui-ci pour indiquer à l’utilisateur que cette url n’est pas valide.

## Tasks

- [ ] TF-073 | Modifier la page "Gestion de projet - mes projets" (Ajouter le bouton)
- [ ] TF-074 | Créer le formulaire
- [ ] TF-075 | Mise à jour de la liste des projets
- [ ] TF-076 | Rédaction des tests
- [ ] TF-077 | Résolution des bugs
