### ISSUE TITLE
US-015 - Lister les achats d’un projet

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#16]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-080, FE-081 |

## User Story

Sur la page “Netlinking > annonceur > Tous les deals”
La liste des deals du projet sélectionné s’affiche au format tableau.
Dans le tableau les colonnes présentes sont:

- le libellé
- support
- type de produit
- l’état de l’offre
- la date de création du deal
- le prix

## Tasks

- [ ] TF-084 | Créer la page "Netlinkings > Annonceur > Tous les deals"
- [ ] TF-084 | Créer le tableau
- [ ] TF-085 | Rédaction des tests
- [ ] TF-086 | Résolution des bugs
