### ISSUE TITLE
US-016 - Vérifier l’état d’un achat

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#17]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-187 |

## User Story

Sur la page “Netlinking > annonceur > Tous les deals”
La liste des deals du projet sélectionné s’affiche sous forme de tableau les colonnes présentes sont:

- le libellé
- support
- type de produit
- l’état de l’offre
- la date de création du deal
- le prix

je peux alors sélectionner un autre onglet ex: “Netlinking > annonceur >  deals actif”.
Les onglets d’état disponible sont: “Tous les deals, Deals en attente,Deals actifs, archives”.

## Tasks

- [ ] TF-087 | Ajouter les onglets "Deals en attente" "Deals actifs" à la page "Netlinkings > Annonceur"
- [ ] TF-088 | Lister les deals en fonction de leur état dans les onglets  "Deals en attente" "Deals actifs"
- [ ] TF-089 | Rédaction des tests
- [ ] TF-090 | Résolution des bugs
