### ISSUE TITLE
US-019 - Activer/Désactiver un compte back office

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#20]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-020 | FE-068 |

## User Story

Sur la page “Administration > Back Office”.
Sur cette page il y a une liste des utilisateurs du back office déjà créé, au bout de chaque ligne il y a une icône (fa-circle-info) 
Je clique sur l'icône.
Une plateforme apparaît,en haut à droite il y a un switch pour modifier l'état d’activation de l’utilisateur.
Je clique sur le switch pour changer le statut de l’utilisateur.

## Tasks

- [ ] TF-101 | Modifier la plateforme d'informations sur un utilisateur back office pour ajouter le switch de statut
- [ ] TF-102 | Mettre à jour les informations de l'interface
- [ ] TF-103 | Rédaction des tests
- [ ] TF-104 | Résolution des bugs
