### ISSUE TITLE
US-020 - Supprimer un compte back office

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#21]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-020 | FE-066 |

## User Story

Sur la page “Administration > Back Office”.
Sur cette page il y a une liste des utilisateurs du back office déjà créé, au bout de chaque ligne il y a une icône (fa-circle-info) 
Je clique sur l'icône.
Une plateforme apparaît avec dedans les informations de l’utilisateur.
Si l’utilisateur est désactivé, en bas de la plateforme il y a un encart. 
Dans cet encart il y a un texte qui explique que la suppression d’un utilisateur est irréversible et un bouton “Supprimer l’utilisateur”.
Je clique sur le bouton.
Une popup apparaît pour demander si l’administrateur est sûr de vouloir supprimer l’utilisateur back office, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer l'utilisateur.

## Tasks

- [ ] TF-105 | Ajouter le bouton de suppression
- [ ] TF-106 | Rédaction des tests
- [ ] TF-107 | Résolution des bugs
