### ISSUE TITLE
US-021 - Ajouter un thème

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#22]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-042 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a un bouton “Ajouter”.
Je clique sur ce bouton.
Une popup apparaît avec dedans un formulaire qui demande les informations suivantes :
- Nom
A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Ajouter le thème”, qui permet d’enregistrer le thème.
Je clique sur le bouton “Ajouter le thème”.

## Tasks

- [ ] TF-108 | Créer la page "Administration > Netlinkings" et l'onglet "Thèmes"
- [ ] TF-109 | Créer le formulaire d'ajout
- [ ] TF-110 | Mettre à jour la liste des thèmes
- [ ] TF-111 | Rédaction des tests
- [ ] TF-112 | Résolution des bugs
