### ISSUE TITLE
US-023 - Ajouter des crédits

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#24]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-028 |

## User Story

Sur la page “Porte-monnaie” je clique sur le bouton “Ajouter des crédits”, un pop-up s’ouvre avec un formulaire contenant le montant que je souhaite ajouter.
je clique sur le bouton “Ajouter” .
Un popup s’ouvre et affiche les informations nécessaires au virement

## Tasks

- [ ] TF-118 | Créer la page “Porte-monnaie”
- [ ] TF-119 | Créer le bouton “Ajouter des crédits” et le pop-up
- [ ] TF-120 | Créer le formulaire + le popup d'infos bancaire
- [ ] TF-121 | Rédaction des tests
- [ ] TF-122 | Résolution des bugs
