### ISSUE TITLE
US-025 - Ajouter un type de produit

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#26]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-045 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet types de produit.
Dans cet onglet il y a un bouton “Ajouter”.
Je clique sur ce bouton.
Une popup apparaît avec dedans un formulaire qui demande les informations suivantes :

- Nom

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Ajouter le type de produit”, qui permet d’enregistrer le thème.
Je clique sur le bouton “Ajouter le type de produit”.

## Tasks

- [ ] TF-128 | Créer la page "Administration > Netlinkings" et l'onglet "Types de produit"
- [ ] TF-129 | Créer le formulaire d'ajout
- [ ] TF-130 | Mettre à jour la liste des types de produit
- [ ] TF-131 | Rédaction des tests
- [ ] TF-132 | Résolution des bugs
