### ISSUE TITLE
US-026 - Modifier un type de produit

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#27]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-0 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de produit existant, au bout de chaque ligne il y a une icône (fa-pen).
Je clique sur l’icône de la ligne du type de produit que je veux modifier.
Une popup apparaît avec dedans un formulaire, pré-remplie avec les informations du type de produit, qui demande les informations suivantes :
- Nom
A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a deux boutons “Enregistrer” et “Annuler”.
Je clique sur le bouton “Enregistrer” pour modifier les informations du type de produit.

## Tasks

- [ ] TF-133 | Modifier la page "Administration > Netlinkings" onglet "Types de produit" ajouter l'icone de modification
- [ ] TF-134 | Créer le formulaire de modification
- [ ] TF-135 | Mettre à jour la liste des types de produit
- [ ] TF-136 | Rédaction des tests
- [ ] TF-137 | Résolution des bugs
