### ISSUE TITLE
US-027 - Supprimer un type de produit

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#28]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-047 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de produit existant, au bout de chaque ligne il y a une icône (fa-trash).
Je clique sur l’icône de la ligne du type de produit que je veux supprimer.
Une popup apparaît pour demander si l’administrateur est sûr de vouloir supprimer le type de produit, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le type de produit.

## Exceptions

1. Le type de produit ne peut être supprimé que s' il n’existe pas de produit relié à ce type, sinon l’administrateur reçoit un message lui expliquant qu’il est impossible de supprimer le type car au moins un produit y est relié.

## Tasks

- [ ] TF-138 | Modifier la page "Administration > Netlinkings" onglet "Types de produit" ajouter l'icone de suppression
- [ ] TF-139 | Créer la popup de suppression
- [ ] TF-140 | Mettre à jour la liste des types de produit
- [ ] TF-141 | Rédaction des tests
- [ ] TF-142 | Résolution des bugs
