### ISSUE TITLE
US-028 - Ajouter un type de support

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#29]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-0 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet types de support.
Dans cet onglet il y a un bouton “Ajouter”.
Je clique sur ce bouton.
Une popup apparaît avec dedans un formulaire qui demande les informations suivantes :
- Nom
A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Ajouter le type de support”, qui permet d’enregistrer le thème.
Je clique sur le bouton “Ajouter le type de support”.

## Tasks

- [ ] TF-143 | Créer la page "Administration > Netlinkings" et l'onglet "Types de support"
- [ ] TF-144 | Créer le formulaire d'ajout
- [ ] TF-145 | Mettre à jour la liste des types de support
- [ ] TF-146 | Rédaction des tests
- [ ] TF-147 | Résolution des bugs
