### ISSUE TITLE
US-030 - Supprimer un type de support

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#31]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-050 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de support existant, au bout de chaque ligne il y a une icône (fa-trash).
Je clique sur l’icône de la ligne du type de support que je veux supprimer.
Une popup apparaît pour demander si l’administrateur est sûr de vouloir supprimer le type de support, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le type de support.

## Exceptions

1. Le type de support ne peut être supprimé que s' il n’existe pas de support relié à ce type, sinon l’administrateur reçoit un message lui expliquant qu’il est impossible de supprimer le type car au moins un support y est relié.

## Tasks

- [ ] TF-153 | Modifier la page "Administration > Netlinkings" onglet "Types de support" ajouter l'icone de suppression
- [ ] TF-154 | Créer la popup de suppression
- [ ] TF-155 | Mettre à jour la liste des types de support
- [ ] TF-156 | Rédaction des tests
- [ ] TF-157 | Résolution des bugs
