### ISSUE TITLE
US-032 - Ajouter un support

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#33]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-026 |

## User Story

Sur la page “Netlinking > Editeur > mes sites”.

Je clique sur le bouton “Ajouter un site”.
Je suis redirigé vers la page de procédure d’ajout de site.

- Etape 1:
  - Url du site 
- Etape 2: 
  - Thématiques du site
  - Présentation du site
  - Pays cible
  - Langue(s)
- Etape 3:
  - Thématiques refusées du site
  - Délai de rédaction
  - optionnellement, remarques dans un textarea prévu à cet effet
- Etape 4 (ajout de produit):
  - prix one-shot
  - nombre de mots.
  - qui rédige entre l’annonceur ou l'éditeur.
  - délai d’acceptation
  - délai de rédaction
  - mention “Article sponsorisé”

Je clique sur “Ajouter”

## Tasks

- [ ] TF-163 | Créer le bouton d'ajout de support
- [ ] TF-164 | Créer les pages de procédure d'ajout de site
- [ ] TF-165 | Créer le formulaire 1
- [ ] TF-166 | Créer le formulaire 2
- [ ] TF-167 | Créer le formulaire 3
- [ ] TF-168 | Créer le formulaire 4
- [ ] TF-169 | Rédaction des tests
- [ ] TF-170 | Résolution des bugs
