### ISSUE TITLE
US-033 - Ajouter un produit

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#34]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-039 |

## User Story

En tant qu’utilisateur je souhaite ajouter un produit, j’accède à la page “Netlinking > Editeur > mes sites”.
La liste de mes sites s’affiche. Un bouton pour chaque site me permet d'éditer les produits disponibles.
je clique sur ce bouton.
La liste des produits actuellement disponibles pour le site sélectionné s’affiche.
un bouton “ajouter un produit” me redirige vers la page d’ajout de produit.
Un formulaire demande les informations suivante :

- prix one-shot
- nombre de mots.
- qui rédige entre l’annonceur ou l'éditeur.
  - délai d’acceptation
  - délai de rédaction
  - mention “Article sponsorisé”

je clique sur le bouton “enregistrer” 
Un message m’indique que le produit a bien été ajouté.

## Tasks

- [ ] TF-171 | Modifier la page "Netlinking > Editeur > Mes sites"
- [ ] TF-172 | Créer le formulaire
- [ ] TF-173 | Mettre à jour l'interface
- [ ] TF-174 | Rédaction des tests
- [ ] TF-175 | Résolution des bugs
