### ISSUE TITLE
US-034 - Visualiser les informations d’un support

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#35]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-034 |

## User Story

Sur la page “Netlinkings > Annonceur > Recherche”.
Après avoir recherché un support, je clique sur la ligne d’un support pour visualiser les informations.
Une plateforme s’ouvre avec les informations suivante : 

- Nom
- favicon
- certificat SSL
- date de création du nom de domaine
- date de première utilisation du nom de domaine,
- les KPIs
- produits proposer
- thèmes
- avis
- screenshots de chaque année depuis la date de première utilisation du nom de domaine

## Tasks

- [ ] TF-176 | Ajouter le bouton pour visualiser les informations.
- [ ] TF-177 | Créer la plateforme
- [ ] TF-178 | Rédaction des tests
- [ ] TF-179 | Résolution des bugs
