### ISSUE TITLE
US-036 - Acheter un article sponsorisé

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#37]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-034 |

## User Story

Sur la page “Netlinkings > Annonceur > Recherche”.
Après avoir fait la recherche d’un support, je clique sur la ligne du support.
Une plateforme apparaît avec les informations du support, en bas de cette plateforme il y a les “produits” que propose le support. Je clique sur le bouton “Faire une offre”.
Je suis rediriger vers la page “Commande”, Sur cette page il y a un formulaire qui demande les informations suivantes :

- Qui doit rédiger l’article ?
- Projet associe (pré-remplie)
- Délai accordé à l'éditeur pour accepter l’offre
- Délai accordé à l'éditeur pour rédiger l’article (Si rédigé par l’éditeur)
- Prix
- Nombre de mot (Si rediger par l’éditeur)
- Brief
- Date d’envoie de l’offre (Maintenant, Programmé, en brouillon)

En bas du formulaire il y a un bouton qui permet d’enregistrer le formulaire.
Je clique sur ce bouton, je suis redirigé vers la page “Netlinkings > Annonceur > Tous les deals et offres”.

## Tasks

- [ ] TF-183 | Créer le bouton “Faire une offre”
- [ ] TF-184 | Créer le formulaire de demande
- [ ] TF-185 | Créer la page commande
- [ ] TF-186 | Rédaction des tests
- [ ] TF-187 | Résolution des bugs
