### ISSUE TITLE
US-037 - Envoyer des messages entre le vendeur et l’acheteur

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#38]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-089 |

## User Story

Sur la page de détails d’un deal
Si le deal est en proposition,en négociation, accepté ou relecture. J’ai la possibilité d’échanger des messages avec la personne avec laquelle le deal est fait.
Les messages sont affichés à la manière d’un chat.
Un textarea permet de renseigner le message à envoyer, j’ai également la possibilité d'ajouter une ou plusieurs pièces jointes. Un bouton “Envoyer”  permet d’envoyer le message

## Tasks

- [ ] TF-188 | Je modifie la page de détails d'un deal pour ajouter le chat
- [ ] TF-189 | Créer le formulaire d'envoie de message
- [ ] TF-190 | Mettre à jour l'interface
- [ ] TF-191 | Rédaction des tests
- [ ] TF-192 | Résolution des bugs
