### ISSUE TITLE
US-038 - Annuler un deal

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#39]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-037 |

## User Story

Sur la page de détails d’un deal.
Si le deal est en brouillon,programmé, en proposition ou en négociation. J’ai la possibilité d’annuler le deal.
un bouton “annuler” affiche un popup et demande une confirmation “Voulez-vous réellement annuler le deal ?”. 
Le popup contient deux boutons, “Oui”,”Non”. je clique sur Oui. 
Un message s’affiche me confirmant la suppression du deal.

## Tasks

- [ ] TF-193 | Créer le bouton "annuler"
- [ ] TF-194 | Créer le popup de confirmation
- [ ] TF-195 | Rédaction des tests
- [ ] TF-196 | Résolution des bugs
