### ISSUE TITLE
TA -001 Mise en place du projet front

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#4]
## Tasks

- [ ] TF-001 | Créer le projet react
- [ ] TF-002 | Importer tous les composants
- [ ] TF-003 | Créer le conteneur
- [ ] TF-004 | Créer le git
- [ ] TF-005 | Ajouter le CI/CD
