### ISSUE TITLE
US-039 - Négocier un prix

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#40]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-035 |

## User Story

Sur la page de détails d’un deal.
Si le deal est en proposition ou en négociation et que le produit permet la négociation. J’ai la possibilité d’échanger sur le prix du produit.
Dans le chat permettant l’échange de message entre vendeur et acheteur. 
En tant qu’acheteur un bouton permet de faire une offre, je renseigne le prix et le nombre de mots, un bouton “Envoyer”  permet d’envoyer l’offre.
En tant que vendeur, l’offre s’affiche dans le chat, avec trois boutons “accepter” ou “refuser” ou contre-offre.
Au bout de 5 offres refusées, le deal est annulé.

## Tasks

- [ ] TF-197 | Je modifie le chat de la page de détails d'un deal pour ajouter les champs nécessaires pour la négociation
- [ ] TF-198 | Mettre à jour l'interface
- [ ] TF-199 | Rédaction des tests
- [ ] TF-200 | Résolution des bugs
