### ISSUE TITLE
US-040 - Archiver un produit

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#41]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-0 |

## User Story

Sur la page “Netlinkings > Editeur > Mes sites”.
Je clique sur la ligne du site qui a le produit que je veux archiver, je suis redirigé vers une page de détails du site.
En bas de cette page il y a les produits du site en format tableau, je clique sur l'icône archiver.
Une popup apparaît pour demander si l’utilisateur est sûr de vouloir supprimer le produit, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le produit.

## Tasks

- [ ] TF-201 | Ajouter le bouton "archiver"
- [ ] TF-202 | Ajouter le popup de confirmation
- [ ] TF-203 | Rédaction des tests
- [ ] TF-204 | Résolution des bugs
