### ISSUE TITLE
US-041 - Modifier un produit

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#42]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-040 |

## User Story

Sur la page “Netlinking > Editeur > mes sites”.
La liste de mes sites s’affiche. Un bouton pour chaque site me permet d'éditer les produits disponibles.
je clique sur ce bouton.
La liste des produits actuellement disponibles pour le site sélectionné s’affiche.
un bouton “éditer” est présent pour chaque produit. Je clique sur le bouton, je suis redirigé  vers la page d’édition de produit.
Un formulaire demande les informations suivante :

- prix one-shot
- nombre de mots.
- qui rédige entre l’annonceur ou l'éditeur.
  - délai d’acceptation
  - délai de rédaction
  - mention “Article sponsorisé”

Je clique sur le bouton “enregistrer” 
Un message m’indique que le produit a bien été modifié.

## Tasks

- [ ] TF-205 | Ajouter le bouton "Modifier"
- [ ] TF-206 | Créer la page d'édition
- [ ] TF-207 | créer le formulaire
- [ ] TF-208 | Rédaction des tests
- [ ] TF-209 | Résolution des bugs
