### ISSUE TITLE
US-042 - Inscrire un support

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#43]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-072 |

## User Story

Sur la page “Administration > Netlinking”.

Je clique sur le bouton “Inscrire un support”.
Je suis redirigé vers la page de procédure d'inscription de support.

- Etape 1:
  - je renseigne l’email du client
- Etape 2:
  - je renseigne l’url du site 
- Etape 3: 
  - je renseigne les thématiques du site
  - je renseigne la présentation du site
- Etape 4:
  - je renseigne les thématiques refusées du site
  - je renseigne si la mention “Article sponsorisé” est présente
  - je renseigne le délai de rédaction
  - optionnellement,je renseigne des remarques dans un textarea prévu à cet effet
- Etape 5:
  - je renseigne le nombre de mots par article
  - je renseigne le montant qui sera chargé aux annonceurs

Je clique sur “Ajouter”

## Tasks

- [ ] TF-210 | Créer le bouton d'ajout de support
- [ ] TF-211 | Créer les pages de procédure d'ajout de site
- [ ] TF-212 | Créer le formulaire 1
- [ ] TF-213 | Créer le formulaire 2
- [ ] TF-214 | Créer le formulaire 3
- [ ] TF-215 | Créer le formulaire 4
- [ ] TF-216 | Rédaction des tests
- [ ] TF-217 | Résolution des bugs
