### ISSUE TITLE
US-003 - Se connecter

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#5]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005 | FE-004 |

## User Story

En tant qu’internaute j'accède au formulaire de connexion via les différents liens disponibles.

Sur cette page, il y a le formulaire de connexion
Le formulaire demande les informations suivantes :
Email
Mot de passe

Je clique sur le bouton “Connexion” en bas du formulaire afin de me connecter.

Si les données saisies sont valides, je suis redirigé vers le tableau de bord de l’application.

## Exceptions

1. Etant donné que le mot de passe et l’adresse mail de l’utilisateur doivent être valides et correspondre au même compte utilisateur, si ce n’est pas le cas on affiche un message d’erreur pour prévenir l’internaute que le mot de passe ou l’adresse email ne sont pas bons.

## Tasks

- [ ] TF-021 | Créer le formulaire de connexion
- [ ] TF-022 | Vérifier que tous les champs sont valide
- [ ] TF-023 | Vérifier si le mot de passe respecter les règles : 8+ caractères, minimum : 1 minuscule, 1 majuscule, 1 chiffre
- [ ] TF-024 | Rediriger l'utilisateur vers le tableau de bord
- [ ] TF-025 | Rédaction des tests
- [ ] TF-026 | Résolution des bugs
