### ISSUE TITLE
US-006 - Modifier mes informations personnelles

### ISSUE THREAD

**Issue by ThomasFont** [MethodzLabs/seo-jungle-react#8]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005 | FE-154 |

## User Story

Sur la page “Paramètres du compte”.
Mes informations personnelles déjà rentrées sont affichées dans un formulaire.
Le formulaire affiche les informations suivantes :

- Nom
- Prénom
- Email
- Numéro de téléphone
- Langue

Je clique sur un des champs pour modifier sa valeur, en cliquant sur le champ deux boutons (Annuler et Enregistrer) apparaissent en bas du formulaire.
Je clique sur le bouton “Enregistrer”, pour sauvegarder les modifications. Et sur “Annuler” pour annuler les modifications.
En cliquant sur l’un des deux boutons pour valider ou non  les modifications, les deux boutons disparaissent.

## Exceptions

1. Étant donné que la longueur maximale du champ nom est 50 et ne doit pas contenir de chiffres ou caractères spéciaux , si il ne correspond pas le champ “Nom” passe au statut invalide avec un message pour expliquer que le nom saisi n’est pas valide
2. Étant donné que la longueur maximale du champ prénom est 50 et ne doit pas contenir de chiffres ou caractères spéciaux , si il ne correspond pas le champ “prénom” passe au statut invalide avec un message pour expliquer que le prénom saisi n’est pas valide

## Tasks

- [ ] TF-043 | Créer la page  "Mon compte - informations personnelles"
- [ ] TF-044 | Créer le formulaire de modifications des informations personnelles
- [ ] TF-045 | Rediriger l'utilisateur vers la page "Mon compte - informations personnelles" avec un message indiquant l'état de la modification ( succès , erreur)
- [ ] TF-046 | Rédaction des tests
- [ ] TF-047 | Résolution des bugs
